services:
  app: 
    container_name: drosophila_project_env
    restart: always
    image: astrabert/silly-gat-kay:latest
    volumes:
      - $USERDATA_PATH:/gatk_modified/userdata
    stdin_open: true
    tty: true
    entrypoint: "/bin/bash"