# latest

FROM astrabert/silly-gat-kay:0.8.0

WORKDIR /gatk_modified

COPY ./shell/installations/conda_install_for_gatk /gatk_modified/conda_install_for_gatk

RUN bash /gatk_modified/conda_install_for_gatk/install_exonerate_freebayes.sh

ENTRYPOINT [ "/bin/bash" ]

# sudo docker build . -f Dockerfile.latest -t astrabert/silly-gat-kay:latest -t astrabert/silly-gat-kay:0.9.0